@startuml database

hide circle

entity Game{
    *id
    --
    *datetime
    *board
    *playerTurn
    *posPlayer1X
    *posPlayer1Y
    *posPlayer2X
    *posPlayer2Y
}


entity User{
    *id
    --
    *isHuman: bool
    email
    name
    password

}

entity QTable {
    *state
    --
    *up
    *down
    *left
    *right
}
note bottom
state =
board +
posPlayer1 +
posPlayer2 +
currentPlayer
end note

entity History {
    *game_id
    *currentPlayer
    --
    *state
    *movement
}


Game }o--|{ User
' note left
' à voir si on garde le
' Many To Many
' pour les relations
' --
' joachim :
' oui puisqu'on aura toujours
' soit 2 joueurs l'un contre l'autre -> 2
' soit 1 joueur contre ia -> 1
' soit 2 ia -> 0
' end note

@enduml